In [1]:
!pip install underthesea

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 19.2/19.2 MB 45.4 MB/s eta 0:00:0000:0100:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 966.9/966.9 kB 59.5 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 599.6/599.6 kB 44.3 MB/s eta 0:00:00


In [2]:
import pandas as pd
from underthesea import word_tokenize 
import string
from gensim.utils import simple_preprocess
import numpy as np

In [3]:
df = pd.read_csv("../input/btmidtermnlp/data.csv")
df.head(5)

title   category  \
0        Galaxy Gear có thể điều khiển TV thông minh  Công nghệ   
1  Nhật – Mỹ định hội đàm chớp nhoáng tại Singapo...   Thế giới   
2         Hàng ngàn học sinh miền núi Nghệ An bỏ học   Giáo dục   
3          'Cô ấy bỏ em vì... em gái trượt đại học?'   Đời sống   
4  Cậu bé vượt qua Face ID của iPhone ngang anh Q...  Công nghệ   

                                             content  
0  Mẫu đồng hồ thông minh Galaxy Gear của Samsung...  
1  >> Phó Tổng thống Mỹ công du châu Á, bàn về Bi...  
2  Hàng ngàn học sinh sau khi tốt nghiệp THCS đã ...  
3  Mr Búp Bê (BB): Hay là bạn phải đến kèm cho cô...  
4  Trang Wired mới đây đưa thông tin cậu bé Ammar...

In [4]:
# def save_Content(ListContent, filename):
#     with open(filename, 'w', encoding='utf-8') as f:
#         for item in ListContent:
#             f.write("%s\n" % item)
#         f.close()

def read_file(file):
    with open(file, 'r', encoding='utf-8') as f:
        line = f.readlines()
        lines = list(m.replace("\n","") for m in line)
        # print(line)
    f.close()
    return lines
# print(lines)

In [5]:
Content = read_file("../input/btmidtermnlp/ListContent.txt")
Content[0:2]

['mẫu đồng_hồ thông_minh galaxy gear samsung ảnh afp slashgear hôm tương_tác tv thông_minh galaxy gear đảm_nhiệm chức_năng kênh âm_lượng tắt tv galaxy gear khả_năng theo_dõi sức_khỏe tức_là thông_tin sức_khỏe của đeo thiết_bị phát tv nắm được sức_khỏe của được hiện galaxy gear có_thể làm_việc các thiết_bị di_động của samsung như galaxy note galaxy tab inch các thiết_bị như galaxy galaxy note sẽ có cập_nhật để tương_tác được với galaxy gear thành luân',
 'phó_tổng_thống mỹ công_du châu_bàn biển đông nhật ký thỏa_thuận quân_sự philippines thủ_tướng nhật shinzo abe dự_kiến hội_đàm hai lãnh_đạo tái cam_kết_thúc_đẩy hợp_tác song_phương tokyowashington kyodo abe sẽ trao_đổi với phó_tổng_thống mỹ về lập_trường của nhật bản tranh_chấp biển đông biển hoa đông chuyến công_du malaysia singapore và philippines của ông abe tăng_cường hợp_tác kinh_tế và an_ninh với các thành_viên của hiệp_hội các quốc_gia đông_nam asean diễn trong bối_cảnh yêu_sách chủ_quyền cứng_rắn của trung_quốc trên biển đông dấ

In [37]:
# flat_list = [x for xs in Content for x in xs]
# flat_list
from sklearn.preprocessing import OneHotEncoder
y = list()
for i in df['category']:
    y.append(i)
# y
y = np.reshape(y,(len(y),1))

# enc.categories_
# flat_list = [x for xs in y for x in xs]
# flat_list
enc = OneHotEncoder(handle_unknown='ignore',sparse = False)
y = enc.fit_transform(y)
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [38]:
y.shape

(51999, 13)

In [14]:
enc.categories_

[array(['Công nghệ', 'Giáo dục', 'Giải trí', 'Khoa học', 'Kinh tế',
        'Nhà đất', 'Pháp luật', 'Thế giới', 'Thể thao', 'Văn hóa', 'Xe cộ',
        'Xã hội', 'Đời sống'], dtype='<U9')]

In [6]:
# data = pd.DataFrame()
# data['content'] = Content
# data['category'] =  df['category']
# word_tokenizen
from nltk.tokenize import word_tokenize
tokenize = list()
for i in Content:
    tokenize.append(word_tokenize(i.lower()))


In [7]:
tokenize[0:2]

[['mẫu',
  'đồng_hồ',
  'thông_minh',
  'galaxy',
  'gear',
  'samsung',
  'ảnh',
  'afp',
  'slashgear',
  'hôm',
  'tương_tác',
  'tv',
  'thông_minh',
  'galaxy',
  'gear',
  'đảm_nhiệm',
  'chức_năng',
  'kênh',
  'âm_lượng',
  'tắt',
  'tv',
  'galaxy',
  'gear',
  'khả_năng',
  'theo_dõi',
  'sức_khỏe',
  'tức_là',
  'thông_tin',
  'sức_khỏe',
  'của',
  'đeo',
  'thiết_bị',
  'phát',
  'tv',
  'nắm',
  'được',
  'sức_khỏe',
  'của',
  'được',
  'hiện',
  'galaxy',
  'gear',
  'có_thể',
  'làm_việc',
  'các',
  'thiết_bị',
  'di_động',
  'của',
  'samsung',
  'như',
  'galaxy',
  'note',
  'galaxy',
  'tab',
  'inch',
  'các',
  'thiết_bị',
  'như',
  'galaxy',
  'galaxy',
  'note',
  'sẽ',
  'có',
  'cập_nhật',
  'để',
  'tương_tác',
  'được',
  'với',
  'galaxy',
  'gear',
  'thành',
  'luân'],
 ['phó_tổng_thống',
  'mỹ',
  'công_du',
  'châu_bàn',
  'biển',
  'đông',
  'nhật',
  'ký',
  'thỏa_thuận',
  'quân_sự',
  'philippines',
  'thủ_tướng',
  'nhật',
  'shinzo',
  'abe',
 

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
# fit_transform the text data to create the feature matrix
X = vectorizer.fit_transform(Content)

In [9]:
vectorizer.get_feature_names_out()

array(['aa', 'aaa', 'aaaa', ..., 'ữu', 'ựa', 'ực'], dtype=object)

In [10]:
X.shape

(51999, 166398)

In [11]:
def vocabulary(content):
    vocab = set()
    [vocab.update(con.split()) for con in content]
    return vocab 

In [12]:
len(vocabulary(Content))

166398

In [21]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [49]:
X_train,y_train

(<34839x166398 sparse matrix of type '<class 'numpy.float64'>'
 	with 5452303 stored elements in Compressed Sparse Row format>,
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.]]))

In [30]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

clf = MLPClassifier(hidden_layer_sizes=(100, 100))

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')

# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

Accuracy: 74.17%
Precision: [0.89567669 0.91858553 0.87478559 0.82943723 0.84112974 0.84052075
 0.84444444 0.91364421 0.96502385 0.76160714 0.96782178 0.73728814
 0.8503937 ]
Recall: [0.7498033  0.83795949 0.7756654  0.73353752 0.7122571  0.76067747
 0.73601148 0.81384615 0.93312836 0.63943028 0.86632201 0.61702128
 0.75524476]
F1 score: [0.81627409 0.87642213 0.82224909 0.77854531 0.77134763 0.79860843
 0.78650824 0.86086249 0.94880813 0.69519152 0.91426345 0.67181467
 0.8       ]
Macro-averaged Precision: 86.46%
Macro-averaged Recall: 76.39%
Macro-averaged F1 score: 81.08%


In [14]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Fit the LabelEncoder to the y data
y = list()
for i in df['category']:
    y.append(i)
# y
# y = np.reshape(y,(len(y),1))
# y
y = label_encoder.fit_transform(y)


In [15]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [16]:
X_train,y_train

(<34839x166398 sparse matrix of type '<class 'numpy.float64'>'
 	with 5452303 stored elements in Compressed Sparse Row format>,
 array([11,  1,  4, ...,  8,  2,  2]))

In [20]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

clf = SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')

# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

Accuracy: 83.28%
Precision: [0.84578696 0.90225564 0.83346066 0.77492877 0.83137255 0.82412791
 0.846875   0.87567153 0.95065536 0.70892351 0.92835596 0.70592885
 0.80830189]
Recall: [0.83713611 0.90022506 0.82965779 0.8330781  0.7922272  0.83505155
 0.77761836 0.87769231 0.94773251 0.75037481 0.90915805 0.7037037
 0.83216783]
F1 score: [0.8414393  0.9012392  0.83155488 0.80295203 0.81132798 0.82955377
 0.81077038 0.87668075 0.94919169 0.72906045 0.91865672 0.70481452
 0.82006126]
Macro-averaged Precision: 83.36%
Macro-averaged Recall: 83.28%
Macro-averaged F1 score: 83.29%


In [18]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
clf = RandomForestClassifier(n_estimators=100)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')
# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

Accuracy: 79.73%
Precision: [0.83453237 0.83835616 0.77854671 0.75549048 0.75789474 0.73656619
 0.77968526 0.82002801 0.92628444 0.73961219 0.89154824 0.72869023
 0.76058394]
Recall: [0.73013375 0.91822956 0.85551331 0.79019908 0.75336323 0.82768778
 0.78192253 0.90076923 0.95618755 0.60044978 0.88035451 0.55240347
 0.80963481]
F1 score: [0.77885019 0.87647691 0.81521739 0.77245509 0.75562219 0.77947295
 0.78080229 0.8585044  0.94099849 0.66280513 0.88591602 0.62841775
 0.78434324]
Macro-averaged Precision: 79.60%
Macro-averaged Recall: 79.67%
Macro-averaged F1 score: 79.38%


In [19]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')
# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

Accuracy: 61.68%
Precision: [0.54826546 0.73390895 0.6272     0.55497382 0.53909159 0.61297539
 0.63928013 0.66279969 0.85789872 0.43400447 0.81226903 0.43104748
 0.57423581]
Recall: [0.57199056 0.70142536 0.59619772 0.56814701 0.54110613 0.60530191
 0.58608321 0.65923077 0.87240584 0.43628186 0.81166913 0.45074862
 0.61305361]
F1 score: [0.55987678 0.71729958 0.61130604 0.56148316 0.54009698 0.60911449
 0.61152695 0.66101041 0.86509146 0.43514019 0.81196897 0.44067797
 0.59301015]
Macro-averaged Precision: 61.75%
Macro-averaged Recall: 61.64%
Macro-averaged F1 score: 61.67%
