In [3]:
!pip install underthesea

In [4]:
import pandas as pd
from underthesea import word_tokenize 
import string
from gensim.utils import simple_preprocess
import numpy as np

In [5]:
df = pd.read_csv("../input/btmidtermnlp/data.csv", encoding = 'utf-8')
df.head(5)

title   category  \
0        Galaxy Gear có thể điều khiển TV thông minh  Công nghệ   
1  Nhật – Mỹ định hội đàm chớp nhoáng tại Singapo...   Thế giới   
2         Hàng ngàn học sinh miền núi Nghệ An bỏ học   Giáo dục   
3          'Cô ấy bỏ em vì... em gái trượt đại học?'   Đời sống   
4  Cậu bé vượt qua Face ID của iPhone ngang anh Q...  Công nghệ   

                                             content  
0  Mẫu đồng hồ thông minh Galaxy Gear của Samsung...  
1  >> Phó Tổng thống Mỹ công du châu Á, bàn về Bi...  
2  Hàng ngàn học sinh sau khi tốt nghiệp THCS đã ...  
3  Mr Búp Bê (BB): Hay là bạn phải đến kèm cho cô...  
4  Trang Wired mới đây đưa thông tin cậu bé Ammar...

In [6]:
# def save_Content(ListContent, filename):
#     with open(filename, 'w', encoding='utf-8') as f:
#         for item in ListContent:
#             f.write("%s\n" % item)
#         f.close()

def read_file(file):
    with open(file, 'r', encoding='utf-8') as f:
        line = f.readlines()
        lines = list(m.replace("\n","") for m in line)
        # print(line)
    f.close()
    return lines
# print(lines)

In [7]:
Content = read_file("../input/btmidtermnlp/ListContent.txt")
Content[0:2]

['mẫu đồng_hồ thông_minh galaxy gear samsung ảnh afp slashgear hôm tương_tác tv thông_minh galaxy gear đảm_nhiệm chức_năng kênh âm_lượng tắt tv galaxy gear khả_năng theo_dõi sức_khỏe tức_là thông_tin sức_khỏe của đeo thiết_bị phát tv nắm được sức_khỏe của được hiện galaxy gear có_thể làm_việc các thiết_bị di_động của samsung như galaxy note galaxy tab inch các thiết_bị như galaxy galaxy note sẽ có cập_nhật để tương_tác được với galaxy gear thành luân',
 'phó_tổng_thống mỹ công_du châu_bàn biển đông nhật ký thỏa_thuận quân_sự philippines thủ_tướng nhật shinzo abe dự_kiến hội_đàm hai lãnh_đạo tái cam_kết_thúc_đẩy hợp_tác song_phương tokyowashington kyodo abe sẽ trao_đổi với phó_tổng_thống mỹ về lập_trường của nhật bản tranh_chấp biển đông biển hoa đông chuyến công_du malaysia singapore và philippines của ông abe tăng_cường hợp_tác kinh_tế và an_ninh với các thành_viên của hiệp_hội các quốc_gia đông_nam asean diễn trong bối_cảnh yêu_sách chủ_quyền cứng_rắn của trung_quốc trên biển đông dấ

In [19]:
# flat_list = [x for xs in Content for x in xs]
# flat_list
from sklearn.preprocessing import OneHotEncoder
y = list()
for i in df['category']:
    y.append(i)
# y
y = np.reshape(y,(len(y),1))
# enc.categories_
# flat_list = [x for xs in y for x in xs]
# flat_list
enc = OneHotEncoder(handle_unknown='ignore',sparse = False)
y = enc.fit_transform(y)
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [20]:
y.shape

(51999, 13)

In [21]:
enc.categories_

[array(['Công nghệ', 'Giáo dục', 'Giải trí', 'Khoa học', 'Kinh tế',
        'Nhà đất', 'Pháp luật', 'Thế giới', 'Thể thao', 'Văn hóa', 'Xe cộ',
        'Xã hội', 'Đời sống'], dtype='<U9')]

In [22]:
# data = pd.DataFrame()
# data['content'] = Content
# data['category'] =  df['category']
# word_tokenizen
# from nltk.tokenize import word_tokenize
# tokenize = list()
# for i in Content:
#     tokenize.append(word_tokenize(i.lower()))


In [23]:
# tokenize[0:2]

In [8]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
# fit_transform the text data to create the feature matrix
X = vectorizer.fit_transform(Content)

In [25]:
vectorizer.get_feature_names_out()

array(['aa', 'aaa', 'aaaa', ..., 'ữu', 'ựa', 'ực'], dtype=object)

In [26]:
X.shape

(51999, 166398)

In [9]:
def vocabulary(content):
    vocab = set()
    [vocab.update(con.split()) for con in content]
    return vocab 

In [10]:
len(vocabulary(Content))

166398

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [30]:
X_train,y_train

(<34839x166398 sparse matrix of type '<class 'numpy.float64'>'
 	with 5452303 stored elements in Compressed Sparse Row format>,
 array([[0., 0., 0., ..., 0., 1., 0.],
        [0., 1., 0., ..., 0., 0., 0.],
        [0., 0., 0., ..., 0., 0., 0.],
        ...,
        [0., 0., 0., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.],
        [0., 0., 1., ..., 0., 0., 0.]]))

In [31]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

clf = MLPClassifier(hidden_layer_sizes=(100, 100))

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')

# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

/opt/conda/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:699: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


Accuracy: 75.06%
Precision: [0.8363047  0.92383292 0.85854456 0.84186472 0.81965812 0.80883473
 0.84576697 0.90364583 0.96945338 0.69270073 0.93764434 0.70069808
 0.83431953]
Recall: [0.81195909 0.84621155 0.79847909 0.70520674 0.71674141 0.7820324
 0.72381636 0.80076923 0.92697925 0.7113943  0.89955687 0.63278172
 0.76689977]
F1 score: [0.8239521  0.88332028 0.82742317 0.7675     0.76475279 0.79520779
 0.78005412 0.84910277 0.94774067 0.70192308 0.9182058  0.66501035
 0.79919028]
Macro-averaged Precision: 84.41%
Macro-averaged Recall: 77.87%
Macro-averaged F1 score: 80.95%


In [11]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Fit the LabelEncoder to the y data
y = list()
for i in df['category']:
    y.append(i)
# y
# y = np.reshape(y,(len(y),1))
# y
y = label_encoder.fit_transform(y)


In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [13]:
X_train,y_train

(<38999x166398 sparse matrix of type '<class 'numpy.float64'>'
 	with 6099257 stored elements in Compressed Sparse Row format>,
 array([ 5, 11,  2, ...,  8,  2,  2]))

In [14]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

clf = SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')

# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

Accuracy: 83.11%
Precision: [0.85088634 0.8892186  0.83449651 0.76438356 0.82676349 0.81844106
 0.82960596 0.88235294 0.95369458 0.71314741 0.93843098 0.6867846
 0.81573705]
Recall: [0.8284264  0.899      0.83783784 0.84205231 0.78989098 0.84
 0.77435388 0.87       0.95369458 0.72764228 0.90690979 0.69327731
 0.8281092 ]
F1 score: [0.83950617 0.89408255 0.83616384 0.80134035 0.80790674 0.8290804
 0.80102828 0.87613293 0.95369458 0.72032193 0.92240117 0.69001568
 0.82187657]
Macro-averaged Precision: 83.11%
Macro-averaged Recall: 83.01%
Macro-averaged F1 score: 83.03%


In [15]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
clf = RandomForestClassifier(n_estimators=100)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')
# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

Accuracy: 79.60%
Precision: [0.84320557 0.83015441 0.76633841 0.74441205 0.74393792 0.75044092
 0.76863504 0.81464738 0.94552529 0.74005305 0.88920726 0.72399445
 0.761079  ]
Recall: [0.73705584 0.914      0.85685686 0.77062374 0.76015857 0.8302439
 0.78926441 0.901      0.95763547 0.56707317 0.89347409 0.54831933
 0.79878665]
F1 score: [0.78656555 0.87006188 0.80907372 0.75729115 0.75196078 0.78832793
 0.77881314 0.85565052 0.95154185 0.64211738 0.89133557 0.62402869
 0.77947706]
Macro-averaged Precision: 79.40%
Macro-averaged Recall: 79.42%
Macro-averaged F1 score: 79.12%


In [16]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')
# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

Accuracy: 61.86%
Precision: [0.55433699 0.7484472  0.64227642 0.54780115 0.55651341 0.59790875
 0.58375125 0.66301097 0.87187187 0.449069   0.83197556 0.4165844
 0.58216433]
Recall: [0.56446701 0.723      0.63263263 0.57645875 0.57581764 0.61365854
 0.57852883 0.665      0.85812808 0.41666667 0.7840691  0.44327731
 0.58746208]
F1 score: [0.55935614 0.73550356 0.63741805 0.56176471 0.56600097 0.60568127
 0.58112831 0.66400399 0.86494538 0.43226147 0.80731225 0.42951654
 0.58480121]
Macro-averaged Precision: 61.89%
Macro-averaged Recall: 61.69%
Macro-averaged F1 score: 61.77%


In [24]:
# flat_list = [x for xs in Content for x in xs]
# flat_list
from sklearn.preprocessing import OneHotEncoder
y = list()
for i in df['category']:
    y.append(i)
# y
y = np.reshape(y,(len(y),1))
# enc.categories_
# flat_list = [x for xs in y for x in xs]
# flat_list
enc = OneHotEncoder(handle_unknown='ignore',sparse = False)
y = enc.fit_transform(y)
y

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [17]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
# fit_transform the text data to create the feature matrix
X = vectorizer.fit_transform(Content)

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [26]:
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

clf = MLPClassifier(hidden_layer_sizes=(100, 100))

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')

# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

/opt/conda/lib/python3.7/site-packages/sklearn/neural_network/_multilayer_perceptron.py:699: UserWarning: Training interrupted by user.
  warnings.warn("Training interrupted by user.")


Accuracy: 76.34%
Precision: [0.87485779 0.9167556  0.8629386  0.83522727 0.80789755 0.83194154
 0.80590717 0.91564928 0.9582505  0.71806167 0.95218295 0.70205479
 0.8362069 ]
Recall: [0.78071066 0.859      0.78778779 0.73943662 0.75024777 0.77756098
 0.75944334 0.825      0.94975369 0.66260163 0.87907869 0.6460084
 0.78463094]
F1 score: [0.8251073  0.88693856 0.82365254 0.78441836 0.77800617 0.80383258
 0.78198567 0.86796423 0.95398318 0.68921776 0.91417166 0.67286652
 0.80959833]
Macro-averaged Precision: 84.75%
Macro-averaged Recall: 78.47%
Macro-averaged F1 score: 81.47%


In [19]:
from sklearn.preprocessing import LabelEncoder

# Create a LabelEncoder object
label_encoder = LabelEncoder()

# Fit the LabelEncoder to the y data
y = list()
for i in df['category']:
    y.append(i)
# y
# y = np.reshape(y,(len(y),1))
# y
y = label_encoder.fit_transform(y)
y

array([0, 7, 1, ..., 3, 3, 3])

In [20]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [21]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score

clf = SVC(kernel='linear')
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')

# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

Accuracy: 75.75%
Precision: [0.71402043 0.84793555 0.73214286 0.73491592 0.68003487 0.76627219
 0.72469636 0.83675565 0.90239044 0.63064008 0.90305585 0.6049896
 0.78369565]
Recall: [0.78071066 0.842      0.73873874 0.74748491 0.77304262 0.75804878
 0.71172962 0.815      0.89261084 0.61077236 0.82245681 0.61134454
 0.72901921]
F1 score: [0.74587779 0.84495735 0.73542601 0.74114713 0.72356215 0.7621383
 0.71815446 0.82573455 0.897474   0.62054724 0.86087393 0.60815047
 0.7553693 ]
Macro-averaged Precision: 75.86%
Macro-averaged Recall: 75.64%
Macro-averaged F1 score: 75.69%


In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
clf = RandomForestClassifier(n_estimators=100)

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')
# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

Accuracy: 79.32%
Precision: [0.83050847 0.81826241 0.76056338 0.76946411 0.75244618 0.73316062
 0.76246334 0.81776557 0.9428848  0.75103164 0.90429688 0.69902913
 0.74105461]
Recall: [0.74619289 0.923      0.86486486 0.76559356 0.76214073 0.82829268
 0.77534791 0.893      0.95960591 0.55487805 0.88867562 0.52941176
 0.79575329]
F1 score: [0.78609626 0.8674812  0.80936768 0.76752395 0.75726243 0.77782868
 0.76885165 0.85372849 0.95117187 0.63822326 0.8964182  0.60251046
 0.76743052]
Macro-averaged Precision: 79.10%
Macro-averaged Recall: 79.13%
Macro-averaged F1 score: 78.80%


In [23]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score
clf = DecisionTreeClassifier()

clf.fit(X_train, y_train)

y_pred = clf.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
precision = precision_score(y_test, y_pred, average=None)
recall = recall_score(y_test, y_pred, average=None)
f1 = f1_score(y_test, y_pred, average=None)
macro_precision = precision_score(y_test, y_pred, average='macro')
macro_recall = recall_score(y_test, y_pred, average='macro')
macro_f1 = f1_score(y_test, y_pred, average='macro')
# print the results
print("Accuracy: {:.2f}%".format(accuracy*100))
print("Precision: {}".format(precision))
print("Recall: {}".format(recall))
print("F1 score: {}".format(f1))
print("Macro-averaged Precision: {:.2f}%".format(macro_precision*100))
print("Macro-averaged Recall: {:.2f}%".format(macro_recall*100))
print("Macro-averaged F1 score: {:.2f}%".format(macro_f1*100))

Accuracy: 61.64%
Precision: [0.55413386 0.74193548 0.65067779 0.54581281 0.53795689 0.58806545
 0.61239496 0.6742268  0.87046124 0.42212675 0.81924198 0.40714995
 0.57868526]
Recall: [0.5715736  0.736      0.62462462 0.55734406 0.56888008 0.59609756
 0.57952286 0.654      0.87389163 0.39939024 0.80902111 0.43067227
 0.58746208]
F1 score: [0.56271864 0.73895582 0.63738509 0.55151817 0.55298651 0.59205426
 0.59550562 0.66395939 0.87217306 0.41044386 0.81409947 0.41858091
 0.58304064]
Macro-averaged Precision: 61.56%
Macro-averaged Recall: 61.45%
Macro-averaged F1 score: 61.49%


In [ ]:
from sklearn.feature_extraction.text import HashingVectorizer
vectorizer = HashingVectorizer()
# fit_transform the text data to create the feature matrix
X = vectorizer.fit_transform(Content)